from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('sfw/waifu', views.sfwwaifu),
    path('sfw/neko', views.sfwneko),
    path('sfw/megumin', views.sfwmegumin),
    path('sfw/shinobu', views.sfwshinobu),
    path('sfw/bully', views.sfwbully),
    path('sfw/cuddle', views.sfwcuddle),
    path('sfw/cry', views.sfwcry),
    path('sfw/hug', views.sfwhug),
    path('sfw/awoo', views.sfwawoo),
    path('sfw/kiss', views.sfwkiss),
    path('sfw/lick', views.sfwlick),
    path('sfw/pat', views.sfwpat),
    path('sfw/smug', views.sfwsmug),
    path('sfw/bonk', views.sfwbonk),
    path('sfw/yeet', views.sfwyeet),
    path('sfw/blush', views.sfwblush),
    path('sfw/smile', views.sfwsmile),
    path('sfw/wave', views.sfwwave),
    path('sfw/highfive', views.sfwhighfive),
    path('sfw/handhold', views.sfwhandhold),
    path('sfw/nom', views.sfwnom),
    path('sfw/bite', views.sfwbite),
    path('sfw/glomp', views.sfwglomp),
    path('sfw/slap', views.sfwslap),
    path('sfw/kill', views.sfwkill),
    path('sfw/kick', views.sfwkick),
    path('sfw/happy', views.sfwhappy),
    path('sfw/wink', views.sfwwink),
    path('sfw/poke', views.sfwpoke),
    path('sfw/dance', views.sfwdance),
    path('sfw/cringe', views.sfwcringe),
    #nsfw
    path('nsfw/waifu', views.nsfwwaifu),
    path('nsfw/neko', views.nsfwneko),
    path('nsfw/trap', views.nsfwtrap),
    path('nsfw/blowjob', views.nsfwblowjob),

]
